[tool.poetry]
name = "yolo"
version = "1"
description = ""
authors = ["Karan Ahlawat <ahlawatkaran12@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
